# Generated by Django 3.2.16 on 2022-10-30 07:56

import django.core.validators
from django.db import migrations, models
import mid_exam.car_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

    ]
