# Generated by Django 3.2.16 on 2022-10-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):


    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(blank=True)),
            ],
        ),
    ]
